server {
    listen 80;
    # This nginx server does not terminate public traffic directly, that is handled by the reverse-proxy Caddy.
    # Therefore, a server name is not required for routing.
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Serve the matching file/directory if it exists, otherwise fall back to index.html so React Router can handle
    # client-side routes.
    location / {
        try_files $uri $uri/ /index.html;
    }
}